### ISSUE TITLE
Site lets you set an empty password, but it will not accept an empty password

### ISSUE THREAD

**Issue by KlipperKyle** [eri-b/mini#1]
Steps to reproduce:

1. Create a first post.
2. Set an empty password by clicking "Add password" without entering anything into the password field.
3. The password is set.  Try logging in with the empty password.  It's a no-go.

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

In my case, I discovered this by accident because I didn't realize that was a text field next to "Add Password".  I'm still laughing at my misfortune.  ;-)

**Comment by eri-b** [comment]
Thanks! A fix will go out with the next push
